CREATE database QLTTN
GO
USE [QLTTN]
GO
CREATE TABLE dbo.BOPHAN(
	MABP nchar(10) NOT NULL, 
	TENBP nvarchar(50)
	CONSTRAINT PK_BOPHAN PRIMARY KEY(MABP),
	CONSTRAINT UK_BOPHAN UNIQUE (TENBP)
)
CREATE TABLE dbo.NHANVIEN(
	MANV nchar(10) NOT NULL,
	HO nvarchar(50),
	TEN nvarchar(50),
	GIOITINH nvarchar(3),
	NGAYSINH date,
	DIACHI ntext,
	SDT nchar(12),
	EMAIL ntext,
	MABP nchar(10)
	CONSTRAINT PK_NHANVIEN PRIMARY KEY(MANV),
	CONSTRAINT FK_NV_BP FOREIGN KEY (MABP) REFERENCES dbo.BOPHAN(MABP)
)

CREATE TABLE dbo.KHACHHANG(
	CCCD nchar(12) NOT NULL,
	HO nvarchar(50),
	TEN nvarchar(50),
	DIACHI ntext,
	SDT nchar(12)
	CONSTRAINT PK_KHACHHANG PRIMARY KEY(CCCD)
)
CREATE TABLE dbo.DICHVU(
	MADV nchar(10),
	TENDV nvarchar(50)
	CONSTRAINT PK_DICHVU PRIMARY KEY(MADV)
)
CREATE TABLE dbo.BANGGIA(
	MAGIA nchar(10),
	BATDAU int,
	KETTHUC int,
	GIA money,
	MADV nchar(10)
	CONSTRAINT PK_BANGGIA PRIMARY KEY(MAGIA)
	CONSTRAINT FK_BANGGIA_DV FOREIGN KEY (MADV) REFERENCES dbo.DICHVU(MADV)

)
CREATE TABLE dbo.DONGHONUOC(
	MADH nchar(10),
	TENDONGHO nvarchar(50),
	LOAIDONGHO nvarchar(50),
	MAKH nchar(12),
	MAGIA nchar(10)
	CONSTRAINT PK_DONGHONUOC PRIMARY KEY(MADH),
	CONSTRAINT FK_DHN_KH FOREIGN KEY (MAKH) REFERENCES dbo.KHACHHANG(CCCD),
	CONSTRAINT FK_DHN_BANGGIA FOREIGN KEY (MAGIA) REFERENCES dbo.BANGGIA(MAGIA)
)

CREATE TABLE dbo.HOADON(
	MAHD nchar(10),
	MADH nchar(10),
	MANV nchar(10), 
	NGAYINHD date,
	CHISODAU int, 
	CHISOCUOI int,
	SONUOCTIEUTHU int, 
	TONGTIEN money
	CONSTRAINT PK_HOADON PRIMARY KEY(MAHD)
	CONSTRAINT FK_HD_DH FOREIGN KEY (MADH) REFERENCES dbo.DONGHONUOC(MADH),
	CONSTRAINT FK_HD_NV FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV)
)
CREATE TABLE dbo.NGUOIQUANLY(
	MAQL nchar(10),
	NGAYNHANCHUC date
	CONSTRAINT PK_QUANLY PRIMARY KEY(MAQL)
)
CREATE TABLE dbo.CTDHN(
	MANV nchar(10),
	MADH nchar(10), 
	NGAYGHI date,
	CHISO int
	CONSTRAINT PK_CTHDN PRIMARY KEY(MANV, MADH)
	CONSTRAINT FK_CTDHN_NV FOREIGN KEY (MANV) REFERENCES dbo.NHANVIEN(MANV),
	CONSTRAINT FK_CTDHN_DH FOREIGN KEY (MADH) REFERENCES dbo.DONGHONUOC(MADH)

)
CREATE TABLE dbo.CT_TDG(
	MAQL nchar(10),
	MAGIA nchar(10), 
	NGAYAPDUNG date, 
	GIAMOI money
	CONSTRAINT PK_CTTDG PRIMARY KEY(MAQL, MAGIA)
	CONSTRAINT FK_CTTDG_QL FOREIGN KEY (MAQL) REFERENCES dbo.NGUOIQUANLY(MAQL),
	CONSTRAINT FK_CTTDG_BANGGIA FOREIGN KEY (MAGIA) REFERENCES dbo.BANGGIA(MAGIA)
)




--USE master
--ALTER DATABASE QLTTN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--DROP database QLTTN